# Generated by Django 4.2 on 2023-10-14 12:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=200)),
                ('logo', models.ImageField(upload_to='ImageLogo')),
                ('mobile', models.CharField(max_length=50)),
                ('comany_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='job_catogery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], max_length=200)),
                ('job_location', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('posted_within', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(choices=[('python devoloper', 'python devoloper'), ('Digtal Marketer', 'Digtal Marketer'), ('Database Administrator', 'Database Administrator'), ('Odoo Devoloper', 'Odoo devoloper')], max_length=100)),
                ('place', models.CharField(max_length=200)),
                ('salary', models.FloatField(verbose_name=range(3500, 4000))),
                ('time_puplish', models.DateTimeField(blank=True, null=True)),
                ('catogory_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job_catogery')),
            ],
        ),
    ]
