# Generated by Django 4.2 on 2023-10-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job_detail',
            options={'verbose_name': 'Propul'},
        ),
    ]
