# Generated by Django 4.2 on 2023-10-14 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_info_employee_info_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_catogery',
            name='experience',
            field=models.IntegerField(default=django.core.validators.MinValueValidator),
        ),
    ]
