# Generated by Django 4.2 on 2023-10-14 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_catogery_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_catogery',
            name='experience',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
