# Generated by Django 4.2 on 2023-10-14 13:08

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_catogery_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_catogery',
            name='experience',
            field=models.IntegerField(validators=[jobs.models.job_catogery.non_negative_validator]),
        ),
    ]
