# Generated by Django 4.2 on 2023-10-14 13:51

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_catogery_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_detail',
            name='product_catogery',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Programming', 'Programming'), ('Sales Erp', 'Sales Erp'), ('Pos Hardware', 'Pos Hardware')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='salary',
            field=models.FloatField(validators=[jobs.models.Job_Detail.Check_Salary]),
        ),
    ]
