# Generated by Django 4.2 on 2023-10-14 18:59

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_detail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[jobs.models.Job_Detail.Check_Salary]),
        ),
    ]
