# Generated by Django 4.2 on 2023-10-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_job_detail_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_detail',
            name='product_catogery',
            field=models.CharField(choices=[('Creative Agency', 'Creative Agency'), ('Programming', 'Programming'), ('Sales Erp', 'Sales Erp'), ('Pos Hardware', 'Pos Hardware')], max_length=100),
        ),
    ]
