# Generated by Django 4.2 on 2023-10-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_job_detail_product_catogery'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_detail',
            name='descripation',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
