# Generated by Django 4.2 on 2023-10-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_job_detail_descripation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_detail',
            old_name='time_puplish',
            new_name='end_apply_job',
        ),
        migrations.AddField(
            model_name='job_detail',
            name='start_apply_job',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
